import os
import re
import logging
import sys
from typing import List, Dict, Optional, Tuple, Generator

from langchain_core.prompts import ChatPromptTemplate
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma.vectorstores import Chroma
from langchain_community.embeddings.fastembed import FastEmbedEmbeddings
from langchain_google_genai import ChatGoogleGenerativeAI
from dotenv import load_dotenv
import chess.engine as chess_engine
import chess

from chess_ai.prompts import prompt
from chess_ai.config import (
    CHESS_PDF_FILENAME,
    DATABASE_DIR,
    CHUNK_SIZE,
    CHUNK_OVERLAP,
    SIMILARITY_SEARCH_K,
    SIMILARITY_SCORE_THRESHOLD,
    ENGINE,
    ENGINE_ANALYSIS_TIME,
    GEMINI_MODEL,
    LOG_LEVEL,
    LOG_LEVEL_DEFAULT,
    FEN_REGEX_PATTERN
)
from chess_ai.utils import (
    ANSI_COLORS,
    RESET_COLORS,
    get_path,
    print_header,
    print_message
)


# Logger setup
logging.basicConfig(level=LOG_LEVEL_DEFAULT)
logger = logging.getLogger(__name__)
logger.setLevel(LOG_LEVEL)

# Global prompt template for LLM context formatting
PROMPT_TEMPLATE: ChatPromptTemplate = ChatPromptTemplate.from_template(prompt)

# Compiled regex for FEN validation
FEN_REGEX = re.compile(FEN_REGEX_PATTERN)

load_dotenv()


def connection_model() -> ChatGoogleGenerativeAI:
    """
    Initialize and return a connection to the Google Gemini API.
    
    Returns:
        ChatGoogleGenerativeAI: Initialized Gemini model instance
        
    Raises:
        ValueError: If API_KEY environment variable is not set
    """
    api_key = os.getenv("API_KEY")
    if not api_key:
        raise ValueError("API_KEY environment variable not found. Please set it in your .env file.")
    model = ChatGoogleGenerativeAI(
        model=GEMINI_MODEL,
        google_api_key=api_key
    )
    return model


def request_model(prompt: str, model: ChatGoogleGenerativeAI) -> Generator[str, None, None]:
    """
    Stream AI response from Google Gemini model.
    
    Yields chunks of text as they are generated by the model, enabling
    real-time streaming for interactive use.
    
    Args:
        prompt: The input prompt/message for the model
        model: The initialized ChatGoogleGenerativeAI model instance
        
    Yields:
        str: Text chunks from the model response
    """
    for chunk in model.stream(prompt):
        if chunk.content:
            yield chunk.content[0]["text"]


def load_pdf_document() -> List:
    """
    Load PDF document from the default chess.pdf file.
    
    Returns:
        List: List of loaded document pages
        
    Raises:
        FileNotFoundError: If the PDF file is not found at the expected path
    """
    pdf_path = get_path(CHESS_PDF_FILENAME)
    logger.info(f"Loading PDF from: {pdf_path}")
    if not os.path.exists(pdf_path):
        raise FileNotFoundError(f"PDF file not found: {pdf_path}")
    pdf_loader = PyPDFLoader(pdf_path)
    document = pdf_loader.load()
    logger.info(f"Successfully loaded PDF: {len(document)} pages")
    return document


def split_pdf_document_into_chunks(documents: List) -> List:
    """
    Split documents into smaller chunks for embedding and retrieval.
    
    Args:
        documents: List of documents to split
        
    Returns:
        List: List of document chunks with preserved metadata
    """
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=CHUNK_SIZE,
        chunk_overlap=CHUNK_OVERLAP,
        length_function=len,
        add_start_index=True
    )
    chunks = splitter.split_documents(documents)
    logger.info(f"Created {len(chunks)} document chunks")
    return chunks


def vectorize_pdf_document_chunks(chunks: List) -> None:
    """
    Create a vector database (Chroma) from document chunks using embeddings.
    
    Args:
        chunks: List of document chunks to vectorize
    """
    logger.info("Initializing embeddings...")
    embedding = FastEmbedEmbeddings()
    db_path = get_path(DATABASE_DIR)
    logger.info(f"Creating vector database at: {db_path}")
    Chroma.from_documents(
        documents=chunks,
        embedding=embedding,
        persist_directory=db_path
    )
    logger.info("Vector database created successfully!")


def create_db() -> None:
    """
    Orchestrate the complete database creation pipeline.
    
    Loads the PDF, splits it into chunks, and creates a vector database.
    
    Raises:
        SystemExit: If any step of the pipeline fails
    """
    logger.info("\n=== Starting database creation pipeline ===")
    try:
        document = load_pdf_document()
        chunks = split_pdf_document_into_chunks(document)
        vectorize_pdf_document_chunks(chunks)
        logger.info("=== Database pipeline completed successfully ===")
    except Exception as e:
        logger.error(f"Database creation failed: {e}")
        sys.exit(1)


def initialize_database() -> Chroma:
    """
    Initialize or load the existing vector database.
    
    Creates a new database if none exists, otherwise loads the existing one.
    
    Returns:
        Chroma: Initialized Chroma vector database instance
    """
    db_path = get_path(DATABASE_DIR)
    if not os.path.exists(db_path):
        logger.info(f"Database not found at {db_path}, creating new one...")
        create_db()
    db = Chroma(
        persist_directory=db_path,
        embedding_function=FastEmbedEmbeddings(),
    )
    logger.info("Database initialized successfully")
    return db


def get_similarity_chunk(message: str, db: Chroma) -> str:
    """
    Retrieve relevant document chunks from the vector database using similarity search.
    
    Args:
        message: The user query to search for
        db: The Chroma vector database instance
        
    Returns:
        str: Concatenated relevant document chunks, separated by newlines
    """
    results = db.similarity_search_with_relevance_scores(
        message,
        k=SIMILARITY_SEARCH_K
    )
    
    # Filter results by relevance score threshold
    result_content = [
        doc[0].page_content
        for doc in results
        if doc[-1] >= SIMILARITY_SCORE_THRESHOLD
    ]
    
    # Join chunks with separator
    information = "\n\n----\n\n".join(result_content)
    logger.debug(f"Retrieved {len(result_content)} relevant chunks from database")
    return information


def get_fen(message: str) -> Optional[str]:
    """
    Extract FEN notation from user message using regex.
    
    Args:
        message: The user message to search for FEN notation
        
    Returns:
        str: The extracted FEN notation, or None if not found
    """
    fen_match = FEN_REGEX.search(message)
    return fen_match.group() if fen_match else None


def validation_fen(message: str) -> Tuple[Optional[chess.Board], Optional[str]]:
    """
    Validate FEN extracted from message and return board or error message.
    
    Args:
        message: The user message containing FEN notation
        
    Returns:
        Tuple[Optional[chess.Board], Optional[str]]: 
            - (chess.Board, None) if FEN is valid
            - (None, error_message) if FEN is invalid
    """
    fen = get_fen(message)
    if not fen:
        return None, "FEN notation not found in message"
    try:
        board = chess.Board(fen)
    except ValueError:
        return None, "Invalid FEN notation"
    if not board.is_valid():
        return None, "FEN contains illegal positions"
    return board, None


def analyse_position(message: str, engine: chess_engine.SimpleEngine) -> Dict:
    """
    Analyze chess position using Stockfish engine if FEN is provided.
    
    Args:
        message: The user message potentially containing FEN notation
        engine: The initialized Stockfish engine instance
        
    Returns:
        Dict with keys:
            - 'error': Error message if FEN is invalid or not found, None if valid
            - 'board': The chess.Board instance if valid, None otherwise
            - 'analysis': Engine analysis result if board is valid, None otherwise
    """
    board, error_fen = validation_fen(message)
    
    if error_fen:
        logger.debug(f"FEN validation failed: {error_fen}")
        return {
            "error": error_fen,
            "board": None,
            "analysis": None
        }
    
    try:
        limit = chess_engine.Limit(time=ENGINE_ANALYSIS_TIME)
        analysis = engine.analyse(board, limit)
        logger.debug(f"Successfully analyzed position")
        return {
            "error": None,
            "board": board,
            "analysis": analysis
        }
    except Exception as e:
        logger.error(f"Engine analysis failed: {e}")
        return {
            "error": f"Engine analysis failed: {str(e)}",
            "board": board,
            "analysis": None
        }


def initialize_engine() -> chess_engine.SimpleEngine:
    """
    Initialize the Stockfish chess engine.
    
    Returns:
        SimpleEngine: Initialized Stockfish engine instance
        
    Raises:
        RuntimeError: If the engine fails to initialize
    """
    try:
        engine = chess_engine.SimpleEngine.popen_uci(ENGINE)
        logger.info(f"Successfully initialized {ENGINE} engine")
        return engine
    except Exception as e:
        logger.error(f"Failed to initialize engine: {e}")
        raise RuntimeError(f"Engine initialization failed: {str(e)}")


def create_prompt(message: str, engine: chess_engine.SimpleEngine, db: Chroma) -> str:
    """
    Create a formatted prompt with context from the database and engine analysis.
    
    Args:
        message: The user's input message
        engine: The initialized Stockfish engine instance
        db: The initialized Chroma vector database
        
    Returns:
        str: The formatted prompt ready for the AI model
    """
    # Analyze position if FEN is provided
    analysis = analyse_position(message, engine)
    
    # Retrieve relevant context from database
    information = get_similarity_chunk(message, db)
    
    # Format prompt with all context
    formatted_prompt = PROMPT_TEMPLATE.invoke(
        {
            "context": information,
            "input": message,
            "engine_analysis": analysis
        }
    )
    
    return formatted_prompt


def interactive_loop(db: Chroma, engine: chess_engine.SimpleEngine, model: ChatGoogleGenerativeAI) -> None:
    """
    Run the main interactive conversation loop.
    
    Args:
        db: The initialized Chroma vector database
        engine: The initialized Stockfish engine
        model: The initialized Gemini model
    """
    while True:
        try:
            message = input(f"{ANSI_COLORS['orange']}\nAsk something: {RESET_COLORS}").strip()
            if not message:
                print("Please enter a valid question!")
                continue
            
            # Create prompt with context and analysis
            prompt = create_prompt(message, engine, db)
            
            # Stream response from model
            for chunk in request_model(prompt, model):
                print(chunk, end="", flush=True)
            
            print()  # New line after response
            
        except KeyboardInterrupt:
            print_message("\n👋 Goodbye!", "green")
            break
        except Exception as e:
            print_message(f"\n❗Error: {e}", "red")
            logger.error(f"Error in interactive loop: {e}")


def main() -> None:
    """
    Main entry point for the Chess AI assistant application.
    
    Initializes all components (database, engine, model) and starts
    the interactive conversation loop.
    """
    # Display welcome header
    print_header()
    
    # Load environment variables
    load_dotenv()
    
    # Initialize AI model
    try:
        model = connection_model()
        logger.info("Gemini model initialized successfully")
    except ValueError as e:
        logger.error(f"Model initialization failed: {e}")
        return
    
    # Initialize vector database
    try:
        db = initialize_database()
    except Exception as e:
        logger.error(f"Database initialization failed: {e}")
        return
    
    # Initialize and run with Stockfish engine
    try:
        with initialize_engine() as engine:
            interactive_loop(db, engine, model)
    except RuntimeError as e:
        logger.error(f"Engine initialization failed: {e}")
        print_message("Failed to initialize Stockfish engine. Please ensure it's installed.", "red")
        return
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
        print_message(f"An unexpected error occurred: {e}", "red")
        return


if __name__ == "__main__":
    main()